version: '3.8'

#фундаментальный блок, которое запускает всё одновременно
services:
  web:
    #указываем путь к папке
    build: ./web-app
    container_name: web_app
    #проброс портов: сначала на моем устройстве потом сервера
    ports:
      - "8098:8098"

  nginx:
    #находим веб-сервер nginx на базе системы alpine
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "80:80"

  client:
    build: ./client-app
    container_name: client
    #задаём порядок запуска, чтобы клиент запустился после запуска web
    depends_on:
      - web
